### ISSUE TITLE
Enable/disable features.

### ISSUE THREAD

**Issue by fiseni** [menees/VsTools#2]
Hi,

Would be nice if there is an option to enable/disable each feature offered in the extension. There is a "Menees" page under "Tools>Options", but those options mostly provide further tweaking of the features. We might need separate page, where all features are listed and the capability of disabling each of them.

The tool is awesome, btw.

**Comment by menees** [comment]
In Menees VS Tools 2019 there are individual pages under Tools > Options > Menees VS Tools:

* General
* Base Converter
* Highlight
* Projects
* Regions
* Sort
* Tasks

Each page already has the ability to enable/disable its relevant features. If I've missed a toggle for some feature please let me know.

**Comment by fiseni** [comment]
Yes, I'm aware of the pages, but not all the functionalities are covered. For an instance, the option to expand/collapse regions.

Not that these options are not working well, it's just usually we may have several extensions installed, and some of the functionalities overlap and can cause conflicts.

**Comment by menees** [comment]
I still don't know what you mean. For the languages where I add #region support (HTML Web Forms, SQL, XAML, XML), I **do** provide options to disable those:

![image](https://user-images.githubusercontent.com/13545825/89715084-db762280-d968-11ea-8c7f-08f6e1914464.png)

If any of these region providers are causing conflicts, just change their "Support X regions" options to False, and they shouldn't apply to new editor instances.

For the region _commands_ like Add Region, Expand All Regions, and Collapse All Regions, there's no need for an option. Commands have to be explicitly invoked, so just don't invoke them if you don't want to use them. If you just want the commands gone from the Menees VS Tools menu or toolbar, then you can already remove them using the Tools > Customize... dialog.

**Comment by fiseni** [comment]
Yes, I was talking about the region commands, Expand All Regions/Collapse All regions. Indeed they have to be explicitly invoked, but the keyboard shortcut is already mapped.

Anyhow, thank you for your elaborate answer. It's not a critical issue actually, we can use workarounds.

**Comment by menees** [comment]
The predefined key bindings are set in the [Menees.VsTools.vsct](https://github.com/menees/VsTools/blob/fc927484121e14464ec80b9bd8435c2bb1008b1d/src/Menees.VsTools/Menees.VsTools.vsct#L605) command table file, which is essentially an embedded resource processed by Visual Studio. I don't programmatically apply those bindings, so I don't have an opportunity to affect them with enable/disable options. Visual Studio applies extension key bindings during install, but you can remove or change them through Tools > Options > Environment > Keyboard.

**Comment by fiseni** [comment]
That's how I'm removing them for now.
I'm not quite familiar with VS ecosystem, so pardon my ignorance. I thought that bindings can be easily mitigated programmatically.

Thank you for your clarification and answers. I'm closing the issue.
