### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by OJacot-Descombes** [menees/VsTools#4]
The README.md only mentions C++ as supported language. In the code I see a Language enum listing different languages. I assume that they are supported as well.

README.MD should be updated to list all supported programming languages.

**Comment by menees** [comment]
Good point! I've been predominantly using C# since 2002, and I haven't used C++ professionally since 2011. So, it never occurred to me that the readme only mentioned C++ (as a historical note) and didn't mention C#. I've updated it now. Thanks!
